#define  HAVE_LIBJPEG     1
#define  HAVE_LIBTIFF     1
#define  HAVE_LIBPNG      1
#define  HAVE_LIBZ        1
#define  HAVE_LIBGIF      1
#define  HAVE_LIBUNGIF    0
#define  HAVE_LIBWEBP     1
#define  HAVE_LIBJP2K     1
#define  LIBJP2K_HEADER   <openjpeg.h>